account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view.as_view(), name='user-login'),
    path('logout/', views.logout_view.as_view(), name='user-logout'),
    path('singup/', views.singup_view.as_view(), name='user-singup'),
    path('profile/<int:user_id>', views.profile_view.as_view(), name='user-profile'),
]

home/urls.py
from django.urls import  path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.HomeView.as_view(), name='home'),
    path('detail/<int:post_id>/<slug:post_slug>/',views.post_detail_view.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>',views.PostDeleteView.as_view(), name='post_delete'),
    path('post/upgrade/<int:post_id>',views.PostUpdateView.as_view(), name='post_update'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace='home')),
    path('account/',include('account.urls', namespace='account')),


]

account/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image")
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f'{self.user} -- {self.slug} -- {self.updated}'
    
    def get_absolute_url(self):
        return reversed('home:post_detial', args = (self.id , self.slug))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class singup_form(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='Enter Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confrim Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))


    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('Youre email wrong')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('Youre username wrong')
        return username
    
   
    
    def clean(self):
        cd = super().clean()
        password1 = cd.get('password1')
        password2 = cd.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError('Youre Password is not mach')
        
class login_form(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(label='Enter Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
                 

home/forms.py
from django import forms
from .models import Post

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body','slug',)

account/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import singup_form , login_form
from home.models import Post
# Create your views here.


class singup_view(View):
    form_class = singup_form
    template_class = 'account/singup.html'

    def dispatch(self, request,*args,**kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request,*args,**kwargs)
        
    def get(self,request):
        form = self.form_class()
        return render(request,self.template_class,{'form':form})
    
    def post(self,reqeust):
        form = self.form_class(reqeust.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password1'])
            messages.success(reqeust,'Account created successfully','success')
            return redirect('home:home')
        return render(reqeust,self.template_class,{'form':form})
    
class login_view(View):
    form_class = login_form
    template_class = 'account/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self,request):
        form = self.form_class()
        return render(request,self.template_class,{'form':form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username = cd['username'], password = cd['password'])
            if user is not None:
                login(request,user)
                messages.success(request,'Account login successfully','success')
                return redirect('home:home')
            else:
                messages.error(request,'Youre password or username is not exist!','warning')
            return render(request,self.template_class,{'form':form})


#Log-out button on Navbar 

class logout_view(LoginRequiredMixin,View):
    def get(self,request):
        logout(request)
        messages.success(request,'You are logout successfully','success')
        return redirect('home:home')
    

class profile_view(LoginRequiredMixin,View):
    def get(self,reqeust,user_id):
        user = User.objects.get(id = user_id)
        posts = Post.objects.filter(user = user)
        return render(reqeust,'account/profile.html',{'user':user, 'posts':posts})
    

home/views.py
#import
from django.shortcuts import render,redirect
from django.views import View
from .models import Post
from django.contrib import messages
from .forms import PostUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class HomeView(View):
    def get(self,request):
        posts = Post.objects.all()
        return render(request,'home/index.html', {'posts':posts})
    
class post_detail_view(View):
    def get(self,request,post_id,post_slug):
        post = Post.objects.get(id = post_id, slug = post_slug)
        return render(request,'home/detail.html',{'post':post}) 



class PostDeleteView(LoginRequiredMixin,View):
    def get(self,request,post_id):
        post = Post.objects.get(id = post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request,'Yorue post delete','success')
        else:
            messages.error(request,'you cant delete this post','danager')
        return redirect('home:home')
    


class PostUpdateView(LoginRequiredMixin,View):
    form_class = PostUpdateForm
    template_class = 'home/update.html'

    def dispatch(self, request, *args, **kwargs):
        post = Post.objects.get(id = kwargs['post_id'])
        if not post.user.id == request.user.id:
            messages.error(request,'you cant delete this post','danager')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self,reqeust,post_id):
        post = Post.objects.get(id = post_id)
        form = self.form_class(instance = post)
        return render(reqeust,self.template_class,{'form':form})
    
    def post(self,request,post_id):
             pass

home/templates/home/detail.html
{% extends 'base.html' %}
    {% block content %}
        
     <p> <a href="{% url 'account:user-profile' post.user.id %}"> {{post.user.username}} </a>{{post.updated|date:"Y-M"}} </p> 
        <p> {{post.image}} </p>
        <p> {{post.slug}} </p>
        <p> {{post.body}} </p>

        {% if request.user.id == post.user.id %}
            <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Updated</a>
        {% endif %}
    {% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
    {% block content %}
        <h3> welcome </h3>
        <div class="card">
            {% for post in posts %}
            <h2> {{post.user}} </h2>
            <a href="{% url 'home:post_detail' post.id post.slug %}" class="card-body"> {{post.body|truncatewords:4}} </a>
            {% endfor %}
        </div>
    {% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}
    {% block content %}
        <h1>Updated</h1>
        <form action="" method="post" class="col-md-2" novalidate>
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Updated">
        </form>
    {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>StackOverflow</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
            crossorigin="anonymous">
        <style>
            .jumbotron{
                padding: 20px;
                margin: 20px;
                background-color: silver;
            }
        </style>
    </head>
    <body>
        {% include 'inc/navbar.html' %}
        <div class="jumbotron">
        {% include 'inc/messages.html' %}
        {% block content %} {% endblock %}
        </div>
    </body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}" >{{msg}}</p>
    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-black bg-black">

        <div class="navbar-nav">
          
            <a class="nav-link active" style="color: white;"  href="{% url 'home:home' %}">Home</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link active" style="color: white;"  href="{% url 'account:user-profile' request.user.id %}">Profile</a>
            <a class="nav-link active" style="color: white;"  href="{% url 'account:user-logout'  %}">Logout</a>
            {% else %}
            <a class="nav-link active"  style="color: white;" href="{% url 'account:user-singup'  %}">Singup</a>
            <a class="nav-link active"  style="color: white;" href="{% url 'account:user-login'  %}">Login</a>
            {% endif %}
            



      </div>
    </div>
  </nav>